### PR TITLE
Enorm

### PR DESCRIPTION
**Pull request by Ryan-Ambrose**
Updated Calibration/Efficiency scripts to use PROOF-lite by default, changed particle ID in calibration script to use normalized energy, make plots more pretty, added ability to update calibration parameters directly.

### CODE REVIEW

**Comment by MarkKJones** [comment]
This is a lot of commits! Will have to look into the conflicts.

**Comment by pooser** [comment]
@Ryan-Ambrose It appears that you have been working off of the same branch for quite some time and thus this pull request is a little intense to say the least.  Not to mention you are pushing in some pdf files and binary files which do not belong here. 

I would suggest that you obtain a fresh up-to-date clone of hallc-replay as well as a clean branch and then move in your changes by hand so that you form a gentle and clear pull request.  This will help avoid any confusion later down the line.

**Comment by vargasa** [comment]
Just a comment. From 6.08, ROOT is working in a set of parallelization tools (alternatives to PROOF-Lite), when using multicore machines rather than multinodes, [take a look](https://root-forum.cern.ch/t/proof-lite-and-customized-class/26219/2).

**Comment by pooser** [comment]
@Ryan-Ambrose can close this PR since it is handled via PR #224?

**Pull request closed without merging**
