### PR TITLE
added files used for shms dc alignment

### PR DESCRIPTION
**Pull request by hszumila**
This includes new parameters in the param file for the shms dc and includes improved alignment values. The python script was used to make histograms for evaluation of the alignment tweaks.

### CODE REVIEW

**Comment by MarkKJones** [comment]
It looks to me that replay_aligndc_shms  needs PARAM/dcalign.param

**Comment by hszumila** [comment]
The file PARAM/dcalign.param is generated by alignDC.py and is a temporary file that is continually overwritten while doing the alignment. This files contains tweaks made to the x,y positions of each plane. I moved the replay_aligndc_shmc script to the CALIBRATION folder. This script is used by the alignDC.py script.

**Comment by hszumila** [comment]
I should also mention that this script will require an updated hcana. I'm cleaning up that directory so that I can push those changes as well.

**Comment by pooser** [comment]
Let's wait until the coinciding changes are propagated into hcana before merging so as to avoid unnecessary problems.

**Comment by hszumila** [comment]
Ok. For now, these changes do nothing.

**Pull request merged**
