### PR TITLE
geometry for shms 

### PR DESCRIPTION
**Pull request by hszumila**
The geometry for specifying the shms drift chambers is no longer commented.

### CODE REVIEW

**Comment by pooser** [comment]
@hszumila Is this PR still alive?  It has conflicts which need to be resolved prior to merging.

**Comment by hszumila** [comment]
The conflicts were spaces/etc. I resolved the differences.

**Comment by hszumila** [comment]
I think this still has to be officially merged.

**Comment by hszumila** [comment]
This also includes some updated scripts for monitoring. When this is merged, I'll delete the branch.

**Pull request merged**
